### ISSUE TITLE
Issue with code

### ISSUE THREAD

**Issue by seyinator** [gsantner/opoc#2]
`List<SimpleM3UParser.M3U_Entry> playlist = new SimpleM3UParser().parse("/filepath/to/streams.m3u");`

I have a problem with this code. Android IDE underlines red parse for some reason. And it says: "Unhandled exception: java.io.IOException" 

How I can fix this?

And where's XML file? How I'm going to list all of them? I don't know. Thanks. And if you can make video about this it will be amazing. I would share.

**Comment by gsantner** [comment]
* 1 - Use try catch around the code
* 2 You can use a simple array adapter. You can find lots of tutorials via internet search for "android simple adapter with picture" or similar. It's not included in Guide/Code as it's pretty generic. The `opoc_filesystem_item.xml` in the repo may be helpful as well.
